# Generated by Django 4.1.4 on 2022-12-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=35)),
                ('author', models.CharField(max_length=15)),
                ('published_year', models.IntegerField(default=0)),
                ('language', models.CharField(max_length=15)),
                ('cost', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'books',
                'db_table': 'book',
                'ordering': ['book_name', 'author'],
            },
        ),
    ]
